### PR TITLE
Application listener

### PR DESCRIPTION
**Pull request by Rishad11**
I went with EventListeners for this application, although I am not quite sure on which events we need for this project. Atleast we have a baseline consisting of ContextRefreshedEvent and ApplicationReadyEvent.

I'll add more if needed or if any of you have any suggestions.

### CODE REVIEW

**Comment by Lucia560** [comment]
Can you see why there are 7 minor issues? It has to do with the package naming that it does not match the convention.

**Review by TrungMa1 — CHANGES_REQUESTED** [review]
i think you need to change all the package names back to springboot_labb2 package to fix the 7 new issues.

**Comment by Lucia560** [comment]
I was about to say the same. All new packages must be in the main package org.example.SpringBoot_labb2.  I realize that org.example is not an ideal naming so we could change that too later .

**Comment by TrungMa1** [comment]
i can see that you also wanted to put the classes into right packages. I have actually already done this in my latest PR. So you can just change the package Application back to Spring boot package and the refactoring of classes into their right packages can be passed in my PR instead.
If you dont understand what i mean, write to me and i'll explain further.

**Comment by Rishad11** [comment]
Yeah, I see now where it went wrong. Thanks for the feedback.

**Pull request closed without merging**
