### PR TITLE
Added main page

### LINKED ISSUE #71: Create a main page
A main page that functions sort of like a relay station, where it forwards users to desired pages, such as view messages, edit profile etc.

### PR DESCRIPTION
**Pull request by Rishad11**
This is a preliminary main page of the website. As mentioned in the issue, there's only links on this page that leads you to other pages. Some functionality is missing as we have yet to to write any user roles and authentication.

If you have any suggestions on improving the layout, the code or whatever, please do tell.

Closes #71

### CODE REVIEW

**Review by BarbieQkiller — DISMISSED** [review]
Great job Rishad!
LGTM and towards the end I could refactor some of the code for consistency in all the files.

**Review by TrungMa1 — COMMENTED** [review]
PR got some conflicts, anyways great job

**Comment by BarbieQkiller** [comment]
Great catch @TrungMa1 then @Rishad11 can solve the conflicts and then we are good to go. Yay!

**Review by TrungMa1 — APPROVED** [review]
Good job Rishad

**Review by BarbieQkiller — APPROVED** [review]
Awesome!

**Pull request merged**
