### PR TITLE
translation on progress

### LINKED ISSUE #107: Translation mess

### PR DESCRIPTION
**Pull request by Lucia560**

### CODE REVIEW

**Comment by Lucia560** [comment]
security fail are in my view. I can totally remove it if necessary

**Comment by BarbieQkiller** [comment]
Should we really save the translated message in the db?
You need something in the GUI that can take you to the translation.
detect language returns a boolean and then turns into a string to check the langague, is that really a correct way of doing this?

**Comment by Lucia560** [comment]
I really don t know. I will check it again . Thats why I asked  previously .

**Comment by BarbieQkiller** [comment]
> I really don t know. I will check it again . Thats why I asked previously .

Sorry I was trying to not sound too harsh.
We shouldn't save the translated messages.

**Comment by Lucia560** [comment]
I like and appreciate honest feedback.  I will modify it for sure.  Thank you😀

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Lucia560** [comment]
totalt fail

**Pull request closed without merging**
