### PR TITLE
modify create, delete, edit messages

### LINKED ISSUE #82: Create and edit messages
A logged in user should be able to create new messages and edit their existing ones.

### PR DESCRIPTION
**Pull request by Lucia560**
I  modified the create , delete, edit methods for messages.

### CODE REVIEW

**Comment by Lucia560** [comment]
I looked at the issues and successfully ignored them for now.

**Comment by BarbieQkiller** [comment]
I have a question. Does this make it possible to change, edit and delete in our GUI. Am missing som thymeleaf stuff possibly?

Meaning the frontend of things 😊❤️

**Comment by Lucia560** [comment]
Exactly, I created an issue for this. We need to check the views for messages edit and create. and some for users too.

**Comment by BarbieQkiller** [comment]
> Exactly, I created an issue for this. We need to check the views for messages edit and create. and some for users too.

Wonderful! Thank you so much for explaining things. I mean that is what I made the message issue for 😊❤️

**Review by BarbieQkiller — APPROVED** [review]
Great job Lucia! 

This makes good stride in the desired direction 😊

**Review by Danback — APPROVED** [review]
Great job!

**Pull request merged**
