### PR TITLE
#36 Add Tests for controllers.

### LINKED ISSUE #36: Add tests for Controllers

### PR DESCRIPTION
**Pull request by Danback**
I've added Tests for controllers with full coverage except for WebController (this will need to be added later on). The tests in general will also need updating as the application progresses, for example it has full coverage but this is not covered as of now:

    @PatchMapping("/messages/{id}/privacy")
    public ResponseEntity<Message> updateMessagePrivacy(@PathVariable Long id, @RequestParam boolean isPrivate) {
        Message updatedMessage = messageService.updateMessageStatus(id, isPrivate);
        return ResponseEntity.ok(updatedMessage);
    }
    
    Other than this part, the tests have full coverage.

### CODE REVIEW

**Comment by Danback** [comment]
Looks like SonarCloud doesn't like the public modifiers, I'll fix it.

**Comment by Danback** [comment]
Issues have now been fixed.

**Review by Lucia560 — APPROVED** [review]
Very well done:) we will keep in mind to update them as we go.

**Review by TrungMa1 — APPROVED** [review]
Good job!

**Pull request merged**
