### PR TITLE
Added GitHub User service.

### PR DESCRIPTION
**Pull request by BarbieQkiller**
This completes our security class.
Automatically creates user in the database.

This PR successfully closes issue #66

### CODE REVIEW

**Review by Lucia560 — DISMISSED** [review]
Very well done:)

**Comment by BarbieQkiller** [comment]
Added another commit to fix the CSRF.

**Review by Lucia560 — APPROVED** [review]
I was ready to have  csrf disabled as this project is just for us

**Review by TrungMa1 — DISMISSED** [review]

**Comment by TrungMa1** [comment]
Shouldnt we try to solve as many issues as possible to maintain best practices? Atleast 3 of them like removing autowired annotation and use constructor injection? Also the one about moving the field value userservice into the method

**Comment by BarbieQkiller** [comment]
> Shouldnt we try to solve as many issues as possible to maintain best practices? Atleast 3 of them like removing autowired annotation and use constructor injection? Also the one about moving the field value userservice into the method

Absolutely 😊

I will do this tomorrow.

**Pull request merged**
