### PR TITLE
#37 add test for service classes

### LINKED ISSUE #37: Add test for Service classes

### PR DESCRIPTION
**Pull request by Danback**
Currently full coverage, might need to add things later on but for now it's covering all lines.

* Add MessageServiceTest.java
* Add UserServiceTest.java
* Add Dependencies for testing

### CODE REVIEW

**Review by Rishad11 — COMMENTED** [review]
Overall, the test code looks good. However, you should fix the issues mentioned by the sonarcloud bot before approval.

**Review by Lucia560 — CHANGES_REQUESTED** [review]
Very well done.) The test dependencies  were added in the previous PR so you might get a merging conflict. Just fix the issues :)

**Review by TrungMa1 — COMMENTED** [review]
Same as the others said, code looks well structured. Just fix the issues. You'll find the solution when pressing on the 4 issues sonar cloud provided. Minor changes and a git merge probably

**Review by Rishad11 — APPROVED** [review]
Great work!

**Review by Lucia560 — APPROVED** [review]
Very well done:)

**Pull request merged**
