### PR TITLE
Made registration connect to login

### PR DESCRIPTION
**Pull request by TrungMa1**
made it possible to get sent to registration view from login view when pressing "create a new account" and vice versa. it is now possible to press "already have an account" if you dont want to create an new account.

this PR is not linked to any issue

### CODE REVIEW

**Comment by BarbieQkiller** [comment]
I am a bit out of the loop, what part of the instructions for the assignment is this?
Or is this a part of where users can change their information, that one I know is listed as a functionality 😄

**Comment by TrungMa1** [comment]
> I am a bit out of the loop, what part of the instructions for the assignment is this? Or is this a part of where users can change their information, that one I know is listed as a functionality 😄

looking back at our requirements for lab2 i can see that there were never a requirement that you should be able to create an account. I didnt really know what was needed and just kept trying to fix any issue our project got. My bad, now that we know we will only need to login with github. shouldnt we delete the whole registration view?

**Comment by BarbieQkiller** [comment]
> > I am a bit out of the loop, what part of the instructions for the assignment is this? Or is this a part of where users can change their information, that one I know is listed as a functionality 😄
> 
> looking back at our requirements for lab2 i can see that there were never a requirement that you should be able to create an account. I didnt really know what was needed and just kept trying to fix any issue our project got. My bad, now that we know we will only need to login with github. shouldnt we delete the whole registration view?

I think it is a great thing and for sure when we have all the basic stuff we could add this as an extra feature. Love the creativity and engagement ❤️

**Review by Danback — APPROVED** [review]
As stated, this isn't a mandatory step for the assignment, nonetheless a neat addition, good job!

**Comment by Danback** [comment]
I'll approve it for now but before merging we could wait until the structure is fully formed? Not sure how we wan't to go about additional features.

**Pull request closed without merging**
